# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html

# Monitor the learning rate during training
# Look at the above link for more detailed information.
learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "epoch"   # interval to log, either step or epoch
  log_momentum: False         # option to also log the momentum values of the optimizer
